### PR TITLE
bare minimum readme

### PR DESCRIPTION
**Pull request by anandijain**

### CODE REVIEW

**Review by fhs — COMMENTED** [review]
This seems to be the same as the docstrings. I'd rather have the documentation be in one and generate the HTML/markdown version automatically. That's what I do for my [NPZ.jl](https://github.com/fhs/NPZ.jl) package. It automatically generated [this page](https://fhs.github.io/NPZ.jl/dev/) using [a github action](https://github.com/fhs/NPZ.jl/blob/master/.github/workflows/docs.yml). A PR to do something similar is welcome.

**Comment by anandijain** [comment]
youd rather have nothing, i dont understand?

**Comment by fhs** [comment]
> youd rather have nothing, i dont understand?

I'd rather have a link to the autogenerated documentation  in the README.

**Comment by pcjentsch** [comment]
currently even that is not there, though

**Pull request closed without merging**
