### PR TITLE
Fix 0.4 deprecations

### PR DESCRIPTION
**Pull request by timholy**
This fixes some 0.4 deprecations. The tests don't actually pass on 0.4 because of some changes in how dates/times are handled. But those seemed a bit incidental, so I didn't try to fix them myself (it's not an area I know well).

### CODE REVIEW

**Comment by fhs** [comment]
I prefer the shorter T(x) instead of convert(T, x). Julia's deprecation warning also suggest T(x):
``
WARNING: uint16(x) is deprecated, use UInt16(x) instead.
``

**Comment by timholy** [comment]
To make it work on both 0.3 and 0.4 it will have to be
```
@compat UInt16(x)
```
You're OK with that? I can change this accordingly if you are.

**Comment by fhs** [comment]
Maybe you used convert so it's compatible with Julia 0.3. I'd use the compat package instead, so that it's easier to change the code to be more idiomatic when support for 0.3 is removed.

**Comment by fhs** [comment]
yes, @compat is nicer

**Comment by timholy** [comment]
OK. Sometimes `@compat` can be more annoying, i.e., in function argument lists it needs to be
```
f(@compat(Float64(3)), @compat(Float64(2)))
```
because of the macro parsing rules. That's not a change you can make by simple search-replace. But that doesn't apply here.

**Comment by timholy** [comment]
actually, there are a couple of examples like that.

**Comment by timholy** [comment]
OK, done. I also converted the capitalization, `Uint->UInt`.

**Comment by fhs** [comment]
Thanks!

**Pull request merged**
