### PR TITLE
Read file backwards to find EOCD offset without conflict

### LINKED ISSUE #62: Reading Zip File fails if _EndCentralDirSig exists in the zipped data
Came across an issue where the `_EndCentralDirSig` aka `0x06054b50` value seems to exist in the zip data itself (which consisted of .XLSX files). The value existed within the last 1024 bytes of the zipped archive that ZipFile.jl seemed to confuse with the `End of central directory record (EOCD)`.

I have crafted a zip file to simulate the failure. 

[A.zip](https://github.com/fhs/ZipFile.jl/files/4067329/A.zip)

### PR DESCRIPTION
**Pull request by fchorney**
Fixes #62 

Since the EOCD will always exist at the end of the file, wouldn't it make more sense to just read the file backwards for the signature, thus ensuring we don't hit any erroneous signatures within the data?

### CODE REVIEW

**Comment by rofinn** [comment]
FWIW, it'd be nice to have 2 commits for this fix.

1. A test zip file that fails and a broken test case and 
2. The 3 character change and working test case.

**Comment by fchorney** [comment]
> 1. A test zip file that fails and a broken test case and
> 2. The 3 character change and working test case.

good idea. This has now been done.

**Comment by rofinn** [comment]
> Is it possible to reproduce the issue with a valid zip file?

Yes, we found this with one of our valid proprietary files (`unzip` works in that case). Shouldn't be too hard to obfuscate those valid files for testing purposes.

**Comment by fchorney** [comment]
Ah yes I see. I shall create a better example. Sorry about that.

**Comment by fchorney** [comment]
I've modified the zip file to be a zip file (created with ZipFile.jl) with an `.XLSX` file in it. Unzips fine with `unzip` (and the modified `ZipFile.jl`) on my end. Please let me know if this works for you now.

**Comment by fchorney** [comment]
I've also been looking at the zip spec and whatnot and noticed that for the general case where there are no zip file comments, the EOCD will be at `filesize - 22`. I figure it's more efficient to just check there first, and if it's not there we can then scan the last 65K for the signature. Since were going bottoms up now, I don't think there's a reason to check the last 1k, and then 65k (aside from using up memory by loading in the data into `b`)

**Comment by fhs** [comment]
Note: ZipFile.jl is based on Go's zip package, which uses the same logic: https://github.com/golang/go/blob/d2de9bd59c068c1bfcb4293de4286196dacf2e43/src/archive/zip/reader.go#L460
I will take a look at the spec later, but maybe we can take care of any optimization in a new PR.

**Comment by fchorney** [comment]
That's fair. I took a quick look through the go implementation issue list and found this https://github.com/golang/go/issues/10464 I theorize it's a similar (or the same) problem. `.jar` files are just zip files, which is the same issue we are experiencing with `.xlsx` files, as they are also just zip files. I'll remove the last commit, and open up a new PR with it at some point.

Just wanted to mention as well, that I was looking at the python implementation of zip, which is essentially what I was basing the fix, and the shortcut off of. https://github.com/python/cpython/blob/3.8/Lib/zipfile.py#L255

**Comment by fchorney** [comment]
Oh actually looking at the go implementation, it looks like it scans from the bottom up as well (assuming I'm reading this correctly). https://github.com/philwebb/go/blob/master/src/archive/zip/reader.go#L421-L433

**Comment by fhs** [comment]
> Oh actually looking at the go implementation, it looks like it scans from the bottom up as well (assuming I'm reading this correctly). https://github.com/philwebb/go/blob/master/src/archive/zip/reader.go#L421-L433

Yep, that's right. I probably overlooked it when I copied the logic from Go's implementation.

**Comment by rofinn** [comment]
Is it possible to get a new release with this change, along with a backport for julia < 1.3?

**Comment by fchorney** [comment]
It looks like 0.9.0 is where julia 1.3 starts being required, so I guess we'd want to do a 0.8.4 patch if possible.

**Comment by fhs** [comment]
Ok, I'll do the releases tonight. I've never done a backport -- hopefully
it works out.

**Comment by fchorney** [comment]
awesome, thanks so much!

**Pull request merged**
