### PR TITLE
Conveniance function: create ZIP file from Dict

### PR DESCRIPTION
**Pull request by samoconnor**
I found that building a .ZIP file from a Dict is very convenient is some situations. e.g.

```julia
function create_lambda(aws, name, jl_code)
    s3_put(aws, aws[:lambda_bucket],
                "$name.zip", zipdict("$name.jl" => jl_code))
    create_lambda(aws, name, "$name.zip")
end
```

### CODE REVIEW

**Comment by fhs** [comment]
I think this belong in a separate, new package built on top of ZipFile. Maybe call it something like ZipFileUtils and put all the helper functions in there.

I've had a request to add other help functions before (see #16), that I rejected. I'd like to keep ZipFile API clean and simple, with only the most basic functions.

Even if I did merge this, you'd need to add an unzipdict function.

**Comment by samoconnor** [comment]
Hi @timholy, did you end up finding a home for your `unzip()` helper function from #16?

**Comment by timholy** [comment]
No, I just left it in Immerse. If you'd like to start something, I'd happily deposit it there.

**Comment by samoconnor** [comment]
Hi @fhs, @timholy,

I've posted a simple convenience ZIP API wrapper incorporating tim's unzip() and my Associative and itterable interfaces here : https://github.com/samoconnor/ZIP.jl

**Comment by timholy** [comment]
Great, thanks!

**Pull request closed without merging**
