### PR TITLE
Move to ZlibBuilder v1.0.4 to fix freebsd

### PR DESCRIPTION
**Pull request by ianshmean**
Should fix the post-test failures at https://github.com/JuliaIO/ImageMagick.jl/pull/156

### CODE REVIEW

**Comment by ianshmean** [comment]
@fhs I've added the `.cirrus.yml` file for freebsd testing on cirrus, that can be enabled here https://github.com/marketplace/cirrus-ci

**Comment by fhs** [comment]
I've enabled cirrus-ci for this repo. Is there a way to trigger the build? I'll try closing and reopening.

**Comment by ianshmean** [comment]
@fhs Thanks! I just committed an empty new line to retrigger and it worked

**Comment by fhs** [comment]
FreeBSD/Julia 1.2 build is failing. Maybe open an issue at https://github.com/ararslan/CirrusCI.jl and disable it for now?

**Comment by ianshmean** [comment]
[Done](https://github.com/ararslan/CirrusCI.jl/issues/1), and done

**Comment by ianshmean** [comment]
Would you mind releasing a new package version to the registry? Trying to get some downstream tests passed on freebsd! thanks!

**Comment by fhs** [comment]
I've tagged v0.8.2.

**Comment by ianshmean** [comment]
Perfect, thanks

**Comment by ianshmean** [comment]
Just checking.. I couldn't find a JuliaRegistrator instruction or PR over in https://github.com/JuliaRegistries/General/pulls

**Comment by fhs** [comment]
JuliaRegistrator wasn't set up. Here is the PR: https://github.com/JuliaRegistries/General/pull/1144.
It's version v0.8.3 now. (I'd rather skip v0.8.2 than modify git tags.)

**Pull request merged**
