### PR TITLE
compare to nothing instead of None to workaround #17

### PR DESCRIPTION
**Pull request by tkelman**
It does look like there might be a julia bug we should report, but in the meantime here's an attempt at a workaround.

### CODE REVIEW

**Comment by fhs** [comment]
looks good to me, if you think we can ignore the build error for now

**Comment by tkelman** [comment]
it passed on mac, interestingly enough

**Comment by tkelman** [comment]
I think I found the bug. https://github.com/JuliaLang/julia/commit/43e283d6535efa793e968964c75e6d60c43b0120#commitcomment-13574174

Good thing your packages' tests exercised these! Can you open an issue with the `None` test code from #17?

**Comment by tkelman** [comment]
Alright, mystery solved. I think this could be merged and the package could be tagged now so it will pass its tests on the about-to-be-released 0.4.0-RC4, then once https://github.com/JuliaLang/julia/pull/13433 gets merged into Julia master the package will be passing tests on nightlies again too.

**Comment by fhs** [comment]
Ok, please merge

**Comment by hayd** [comment]
Before you tag consider merging #21 which removes all the deprecations. :)

**Pull request merged**
