### PR TITLE
added zip64 support for readers

### PR DESCRIPTION
**Pull request by barcharcraz**
I needed to use this library to read very large (~30-300Gb) Zip Archives. So I added support for Zip64 to readers. I changed the fields of ReadableFile to be 64-bit and added code to get the central directory offset from the zip64 end central directory locater. I also added support for pulling offsets and file sizes from the zip64 extended info section.

### CODE REVIEW

**Comment by fhs** [comment]
Thanks for working on this.

Can you also add some tests? You can add a small zip64 file similar to test/infozip.zip and check you can read it.

**Comment by barcharcraz** [comment]
sure. although for testing 64bit offsets the file actually needs to be >4gb

**Comment by fhs** [comment]
Of course, we're not going to add >4gb file to the repo, so there is no need to test 64bit offset. But some amount of testing is needed to exercise the code.

If you need ideas, see how it's done in Go: https://golang.org/src/archive/zip/testdata/ and https://golang.org/src/archive/zip/reader_test.go

**Comment by fhs** [comment]
Merged #88. Thanks for the initial work for zip64 support!

**Pull request closed without merging**
